project_id = "qtjitszradxsmnilnqtj"
[functions.chatwoot-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/chatwoot-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatwoot-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatwoot-webhook/*.html" ]

[functions.ai-auditor]
enabled = true
verify_jwt = false
import_map = "./functions/ai-auditor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-auditor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-auditor/*.html" ]

[functions.chatwoot-sync-messages]
enabled = true
verify_jwt = false
import_map = "./functions/chatwoot-sync-messages/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatwoot-sync-messages/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatwoot-sync-messages/*.html" ]

[functions.chatwoot-metrics-sync]
enabled = true
verify_jwt = false
import_map = "./functions/chatwoot-metrics-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatwoot-metrics-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatwoot-metrics-sync/*.html" ]

[functions.transcribe-audio]
enabled = true
verify_jwt = false
import_map = "./functions/transcribe-audio/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/transcribe-audio/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/transcribe-audio/*.html" ]
