project_id = "qtjitszradxsmnilnqtj"

[functions.ai-autonomous-evaluator]
enabled = true
verify_jwt = false
entrypoint = "./functions/ai-autonomous-evaluator/index.ts"

[functions.daily-score-snapshot]
enabled = true
verify_jwt = false
entrypoint = "./functions/daily-score-snapshot/index.ts"

[functions.chatwoot-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/chatwoot-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatwoot-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatwoot-webhook/*.html" ]

[functions.ai-auditor]
enabled = true
verify_jwt = false
import_map = "./functions/ai-auditor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-auditor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-auditor/*.html" ]

[functions.chatwoot-sync-messages]
enabled = true
verify_jwt = false
import_map = "./functions/chatwoot-sync-messages/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatwoot-sync-messages/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatwoot-sync-messages/*.html" ]

[functions.chatwoot-metrics-sync]
enabled = true
verify_jwt = false
import_map = "./functions/chatwoot-metrics-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatwoot-metrics-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatwoot-metrics-sync/*.html" ]

[functions.transcribe-audio]
enabled = true
verify_jwt = false
import_map = "./functions/transcribe-audio/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/transcribe-audio/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/transcribe-audio/*.html" ]

[functions.chatwoot-action]
enabled = true
verify_jwt = false
import_map = "./functions/chatwoot-action/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatwoot-action/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatwoot-action/*.html" ]

[functions.admin-create-user]
enabled = true
verify_jwt = false
import_map = "./functions/admin-create-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-create-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-create-user/*.html" ]

[functions.ai-daily-consolidator]
enabled = true
verify_jwt = false
import_map = "./functions/ai-daily-consolidator/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-daily-consolidator/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-daily-consolidator/*.html" ]

[functions.recalc-lost-scores]
enabled = true
verify_jwt = false
import_map = "./functions/recalc-lost-scores/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/recalc-lost-scores/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/recalc-lost-scores/*.html" ]

[functions.ai-feedback-embedder]
enabled = true
verify_jwt = false
import_map = "./functions/ai-feedback-embedder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-feedback-embedder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-feedback-embedder/*.html" ]

[functions.ai-weekly-inquisitor]
enabled = true
verify_jwt = false
import_map = "./functions/ai-weekly-inquisitor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-weekly-inquisitor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-weekly-inquisitor/*.html" ]
