// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkqgfdftwravypdxxxln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcWdmZGZ0d3JhdnlwZHh4eGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mjk5MTAsImV4cCI6MjA2NTQwNTkxMH0.5X9SiM2Bj6hReTR3eILTCR9R4UMrTBa0tnNGB8R0Pr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);